app/src/main/AndroidManifest.xml, app/src/main/java/cloud/shoplive/sample/fragment/MainFragment.kt, app/src/main/res/anim/slide_in_left.xml, app/src/main/res/anim/slide_in_right.xml, app/src/main/res/anim/slide_out_left.xml, app/src/main/res/anim/slide_out_right.xml, app/src/main/res/drawable/progress_animation1.xml, app/src/main/res/drawable/progress_animation2.xml, app/src/main/res/drawable/splash_background.xml, app/src/main/res/drawable/splash_bg.xml, app/src/main/res/drawable/splash_logo.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_webview.xml, app/src/main/res/layout/alert.xml, app/src/main/res/layout/appbar_main.xml, app/src/main/res/layout/custom_action_dialog.xml, app/src/main/res/layout/custom_share_dialog.xml, app/src/main/res/layout/dialog_webview.xml, app/src/main/res/layout/fragment_campaign.xml, app/src/main/res/layout/fragment_main.xml, app/src/main/res/layout/fragment_signin.xml, app/src/main/res/layout/fragment_user.xml, app/src/main/res/layout/input_dialog.xml, app/src/main/res/menu/campaign_menu.xml, app/src/main/res/menu/user_menu.xml, app/src/main/res/navigation/navigation_graph.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
- 링크 넣는 부분
- 메인화면에 SDK 버전 추가했습니다.
- 유틸 설명 쓰는 부분
=> sdk version 표시

app/build.gradle, build.gradle
=> sdk v1.2.5 적용

app/build.gradle
=> sdk v1.2.7 적용

app/src/main/java/cloud/shoplive/sample/MainActivity.kt, app/src/main/java/cloud/shoplive/sample/SampleActivity.java, app/src/main/java/cloud/shoplive/sample/fragment/MainFragment.kt
=> ShopLive.init(application) 코드 제거

app/src/main/java/cloud/shoplive/sample/fragment/MainFragment.kt
- Set user when pip mode (v1.2.7)
=> Set user when pip mode (v1.2.7)

app/build.gradle
=> minifyEnabled true

app/build.gradle, app/src/main/AndroidManifest.xml
=> Wrapping ExoPlayer Lib

app/build.gradle
=> sdk v1.2.7.1 적용

app/build.gradle, app/src/main/AndroidManifest.xml
=> Updated shoplive-sdk v1.3.1

app/src/main/AndroidManifest.xml, app/src/main/java/cloud/shoplive/sample/CampaignSettings.kt, app/src/main/java/cloud/shoplive/sample/DeeplinkInfo.kt, app/src/main/java/cloud/shoplive/sample/MainActivity.kt, app/src/main/java/cloud/shoplive/sample/MainViewModel.kt, app/src/main/java/cloud/shoplive/sample/SchemeActivity.kt, app/src/main/java/cloud/shoplive/sample/fragment/CampaignFragment.kt, app/src/main/java/cloud/shoplive/sample/fragment/MainFragment.kt, app/src/main/res/layout/activity_main.xml
=> Added deeplink sample

app/build.gradle
=> Updated shoplive-sdk v1.3.2

app/build.gradle, app/src/main/java/cloud/shoplive/sample/fragment/SettingsFragment.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Updated module version

app/build.gradle
=> Updated shoplive-sdk v1.3.4

app/src/main/java/cloud/shoplive/sample/Options.kt, app/src/main/java/cloud/shoplive/sample/fragment/MainFragment.kt, app/src/main/java/cloud/shoplive/sample/fragment/SettingsFragment.kt, app/src/main/res/layout/fragment_main.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/settings.xml
=> Changed sample code for preview

app/build.gradle
=> Updated shoplive-sdk v1.4.0

app/build.gradle
=> Updated shoplive-sdk v1.4.1

app/build.gradle
- Updated the Shopive-exoplayer version to 2.18.1.4.
- 유틸 설명 쓰는 부분
=> Updated the Shopive-exoplayer version to 2.18.1.4.

app/build.gradle, app/src/main/java/cloud/shoplive/sample/shortform/ShortformCardFragment.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformHorizontalFragment.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformVerticalFragment.kt
=> Updated shoplive-sdk v1.4.2

README.md
- README 에 적용된 버전값 1.4.3으로 최신 버전 적용
=> Modified to the latest sdk version(v1.4.3) in the README document.

README.md, app/build.gradle, app/src/main/java/cloud/shoplive/sample/views/main/MainActivity.kt
=> Version bump to v1.4.5

app/src/main/java/cloud/shoplive/sample/shortform/HybridShortformActivity.kt, app/src/main/java/cloud/shoplive/sample/shortform/NativeShortformActivity.kt
- Fix a share interface parameter
=> Fix a share interface parameter

app/build.gradle, app/src/main/java/cloud/shoplive/sample/PreferencesUtil.kt, app/src/main/java/cloud/shoplive/sample/extension/NumberExtension.kt, app/src/main/java/cloud/shoplive/sample/shortform/NativeShortformActivity.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformFragments.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformOptionDialog.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformSampleAdapter.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformSampleData.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformViewModel.kt, app/src/main/res/layout/activity_native_shortform.xml, app/src/main/res/layout/dialog_shortform_option.xml, app/src/main/res/layout/fragment_shortform_card_type.xml, app/src/main/res/layout/fragment_shortform_horizontal_type.xml, app/src/main/res/layout/fragment_shortform_vertical_type.xml, app/src/main/res/values/strings.xml
- Bump version v1.4.6 & Add a shortform option dialog
=> Bump version v1.4.6 & Add a shortform option dialog

README.md, app/build.gradle, app/src/main/java/cloud/shoplive/sample/shortform/HybridShortformActivity.kt, app/src/main/java/cloud/shoplive/sample/shortform/NativeShortformActivity.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformMainFragments.kt, app/src/main/java/cloud/shoplive/sample/shortform/ShortformSampleAdapter.kt, app/src/main/java/cloud/shoplive/sample/views/main/MainActivity.kt, gradle.properties
=> Bump version to v1.5.5

app/proguard-rules.pro
- https://stackoverflow.com/questions/65077282/why-does-minify-cause-error-jsonobjectrewards-not-a-string
- Add a proguard rules for JSONObject
=> Add a proguard rules for JSONObject

app/src/main/java/cloud/shoplive/sample/views/main/MainActivity.kt
- Add a conversion event sample code
=> Add a conversion event sample code

app/src/main/java/cloud/shoplive/sample/views/main/MainActivity.kt
- Fix a custom share dialog sample
=> Fix a custom share dialog sample

app/proguard-rules.pro
- Fix a groguard rules for Gson
=> Fix a proguard rules for Gson

.github/workflows/build.yml, app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Bump gradle, kotlin version
